public class NewtonController {
    //This controller does math using the Newton API
    //https://github.com/aunyks/newton-api  

    //TODO #6- add more Newton ops
    private static final String[] OPERATIONS = new list<String> {'derive'};

    //Todo #5 - call the calculate function to demo
    public String demoCalculate(){
        return '';
    }

    //todo implement calcualte, call http service
    public String calculate(String operation, String expression){
        //TODO #1 - Error handling if invalid ops is called

        //TODO #2 - Newton docs day expression must be url encoded

        //TODO #3 - Build the endpoint url

        //TODO #4
        //HttpCalloutService.makeRequest(endpointUrl)
        return '';
    }
}
